"""create recharge table

Revision ID: 9f49a48322e6
Revises: 776f108912c0
Create Date: 2026-09-20 12:30:41.736590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f49a48322e6'
down_revision: Union[str, Sequence[str], None] = '776f108912c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recharge_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference')
    )
    op.create_index(op.f('ix_recharges_created_at'), 'recharges', ['created_at'], unique=False)
    op.create_index(op.f('ix_recharges_customer_id'), 'recharges', ['customer_id'], unique=False)
    op.create_index('ix_recharges_customer_status_created', 'recharges', ['customer_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_recharges_recharge_id'), 'recharges', ['recharge_id'], unique=True)
    op.create_index(op.f('ix_recharges_status'), 'recharges', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recharges_status'), table_name='recharges')
    op.drop_index(op.f('ix_recharges_recharge_id'), table_name='recharges')
    op.drop_index('ix_recharges_customer_status_created', table_name='recharges')
    op.drop_index(op.f('ix_recharges_customer_id'), table_name='recharges')
    op.drop_index(op.f('ix_recharges_created_at'), table_name='recharges')
    op.drop_table('recharges')
    # ### end Alembic commands ###
