"""create transaction

Revision ID: b9a16f8754e5
Revises: 9f49a48322e6
Create Date: 2026-09-20 14:09:17.749376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a16f8754e5'
down_revision: Union[str, Sequence[str], None] = '9f49a48322e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sender_customer_id', sa.Integer(), nullable=True),
    sa.Column('receiver_customer_id', sa.Integer(), nullable=True),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sender_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_receiver_customer_id'), 'transactions', ['receiver_customer_id'], unique=False)
    op.create_index('ix_transactions_receiver_status_created', 'transactions', ['receiver_customer_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_sender_customer_id'), 'transactions', ['sender_customer_id'], unique=False)
    op.create_index('ix_transactions_sender_status_created', 'transactions', ['sender_customer_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index('ix_transactions_sender_status_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_customer_id'), table_name='transactions')
    op.drop_index('ix_transactions_receiver_status_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
