"""craete merchange table

Revision ID: fd6cd48ee308
Revises: b9a16f8754e5
Create Date: 2026-09-20 14:34:15.286480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6cd48ee308'
down_revision: Union[str, Sequence[str], None] = 'b9a16f8754e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('merchant_category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_merchant_id'), 'merchants', ['merchant_id'], unique=True)
    op.create_index(op.f('ix_merchants_status'), 'merchants', ['status'], unique=False)
    op.create_table('merchant_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference')
    )
    op.create_index(op.f('ix_merchant_payments_created_at'), 'merchant_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_merchant_payments_customer_id'), 'merchant_payments', ['customer_id'], unique=False)
    op.create_index('ix_merchant_payments_customer_status_created', 'merchant_payments', ['customer_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_merchant_payments_idempotency_key'), 'merchant_payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_merchant_payments_merchant_id'), 'merchant_payments', ['merchant_id'], unique=False)
    op.create_index('ix_merchant_payments_merchant_status_created', 'merchant_payments', ['merchant_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_merchant_payments_payment_id'), 'merchant_payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_merchant_payments_status'), 'merchant_payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_payments_status'), table_name='merchant_payments')
    op.drop_index(op.f('ix_merchant_payments_payment_id'), table_name='merchant_payments')
    op.drop_index('ix_merchant_payments_merchant_status_created', table_name='merchant_payments')
    op.drop_index(op.f('ix_merchant_payments_merchant_id'), table_name='merchant_payments')
    op.drop_index(op.f('ix_merchant_payments_idempotency_key'), table_name='merchant_payments')
    op.drop_index('ix_merchant_payments_customer_status_created', table_name='merchant_payments')
    op.drop_index(op.f('ix_merchant_payments_customer_id'), table_name='merchant_payments')
    op.drop_index(op.f('ix_merchant_payments_created_at'), table_name='merchant_payments')
    op.drop_table('merchant_payments')
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_merchant_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
