from enum import Enum


class Intent(str, Enum):
    GENERAL = "GENERAL"
    KNOWLEDGE = "KNOWLEDGE"
    CUSTOMER_INFO = "CUSTOMER_INFO"
    KYC = "KYC"
    WALLET = "WALLET"
    RECHARGE = "RECHARGE"
    TRANSACTION = "TRANSACTION"
    MERCHANT_PAYMENT = "MERCHANT_PAYMENT"
    SUPPORT_TICKET = "SUPPORT_TICKET"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"